contact_links:
  - name: Join Greengage users mailing list
    url: https://groups.google.com/a/greenplum.org/g/gpdb-users
    about: Please ask  general questions here.
  - name: Join Greengage developers mailing list
    url: https://groups.google.com/a/greenplum.org/g/gpdb-dev
    about: Please ask developing questions here.
