/*-------------------------------------------------------------------------
 *
 * gp_configuration_history_d.h
 *    Macro definitions for gp_configuration_history
 *
 * Portions Copyright (c) 1996-2023, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef GP_CONFIGURATION_HISTORY_D_H
#define GP_CONFIGURATION_HISTORY_D_H

#define GpConfigHistoryRelationId 5106

#define Anum_gp_configuration_history_time 1
#define Anum_gp_configuration_history_dbid 2
#define Anum_gp_configuration_history_desc 3

#define Natts_gp_configuration_history 3


#endif							/* GP_CONFIGURATION_HISTORY_D_H */
