/*-------------------------------------------------------------------------
 *
 * gp_distribution_policy_d.h
 *    Macro definitions for gp_distribution_policy
 *
 * Portions Copyright (c) 1996-2023, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef GP_DISTRIBUTION_POLICY_D_H
#define GP_DISTRIBUTION_POLICY_D_H

#define GpPolicyRelationId 7142
#define GpPolicyLocalOidIndexId 8103

#define Anum_gp_distribution_policy_localoid 1
#define Anum_gp_distribution_policy_policytype 2
#define Anum_gp_distribution_policy_numsegments 3
#define Anum_gp_distribution_policy_distkey 4
#define Anum_gp_distribution_policy_distclass 5

#define Natts_gp_distribution_policy 5


#endif							/* GP_DISTRIBUTION_POLICY_D_H */
