/*-------------------------------------------------------------------------
 *
 * gp_fastsequence_d.h
 *    Macro definitions for gp_fastsequence
 *
 * Portions Copyright (c) 1996-2023, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef GP_FASTSEQUENCE_D_H
#define GP_FASTSEQUENCE_D_H

#define FastSequenceRelationId 8043
#define FastSequenceObjidObjmodIndexId 6067

#define Anum_gp_fastsequence_objid 1
#define Anum_gp_fastsequence_objmod 2
#define Anum_gp_fastsequence_last_sequence 3

#define Natts_gp_fastsequence 3


#endif							/* GP_FASTSEQUENCE_D_H */
