/*-------------------------------------------------------------------------
 *
 * gp_id_d.h
 *    Macro definitions for gp_id
 *
 * Portions Copyright (c) 1996-2023, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef GP_ID_D_H
#define GP_ID_D_H

#define GpIdRelationId 5101

#define Anum_gp_id_gpname 1
#define Anum_gp_id_numsegments 2
#define Anum_gp_id_dbid 3
#define Anum_gp_id_content 4

#define Natts_gp_id 4


#endif							/* GP_ID_D_H */
