/*-------------------------------------------------------------------------
 *
 * gp_partition_template_d.h
 *    Macro definitions for gp_partition_template
 *
 * Portions Copyright (c) 1996-2023, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef GP_PARTITION_TEMPLATE_D_H
#define GP_PARTITION_TEMPLATE_D_H

#define PartitionTemplateRelationId 8022
#define GpPartitionTemplateRelidLevelIndexId 8023

#define Anum_gp_partition_template_relid 1
#define Anum_gp_partition_template_level 2
#define Anum_gp_partition_template_template 3

#define Natts_gp_partition_template 3


#endif							/* GP_PARTITION_TEMPLATE_D_H */
