/*-------------------------------------------------------------------------
 *
 * gp_segment_configuration_d.h
 *    Macro definitions for gp_segment_configuration
 *
 * Portions Copyright (c) 1996-2023, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef GP_SEGMENT_CONFIGURATION_D_H
#define GP_SEGMENT_CONFIGURATION_D_H

#define GpSegmentConfigRelationId 8036
#define GpSegmentConfigContentPreferred_roleIndexId 7139
#define GpSegmentConfigDbidIndexId 7140

#define Anum_gp_segment_configuration_dbid 1
#define Anum_gp_segment_configuration_content 2
#define Anum_gp_segment_configuration_role 3
#define Anum_gp_segment_configuration_preferred_role 4
#define Anum_gp_segment_configuration_mode 5
#define Anum_gp_segment_configuration_status 6
#define Anum_gp_segment_configuration_port 7
#define Anum_gp_segment_configuration_hostname 8
#define Anum_gp_segment_configuration_address 9
#define Anum_gp_segment_configuration_datadir 10

#define Natts_gp_segment_configuration 10


#endif							/* GP_SEGMENT_CONFIGURATION_D_H */
