/*-------------------------------------------------------------------------
 *
 * gp_version_at_initdb_d.h
 *    Macro definitions for gp_version_at_initdb
 *
 * Portions Copyright (c) 1996-2023, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef GP_VERSION_AT_INITDB_D_H
#define GP_VERSION_AT_INITDB_D_H

#define GpVersionRelationId 5103

#define Anum_gp_version_at_initdb_schemaversion 1
#define Anum_gp_version_at_initdb_productversion 2

#define Natts_gp_version_at_initdb 2


#endif							/* GP_VERSION_AT_INITDB_D_H */
