/*-------------------------------------------------------------------------
 *
 * pg_appendonly_d.h
 *    Macro definitions for pg_appendonly
 *
 * Portions Copyright (c) 1996-2023, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef PG_APPENDONLY_D_H
#define PG_APPENDONLY_D_H

#define AppendOnlyRelationId 6105
#define AppendOnlyRelidIndexId 7141

#define Anum_pg_appendonly_relid 1
#define Anum_pg_appendonly_blocksize 2
#define Anum_pg_appendonly_safefswritesize 3
#define Anum_pg_appendonly_compresslevel 4
#define Anum_pg_appendonly_checksum 5
#define Anum_pg_appendonly_compresstype 6
#define Anum_pg_appendonly_columnstore 7
#define Anum_pg_appendonly_segrelid 8
#define Anum_pg_appendonly_blkdirrelid 9
#define Anum_pg_appendonly_blkdiridxid 10
#define Anum_pg_appendonly_visimaprelid 11
#define Anum_pg_appendonly_visimapidxid 12

#define Natts_pg_appendonly 12


#endif							/* PG_APPENDONLY_D_H */
