/*-------------------------------------------------------------------------
 *
 * pg_attribute_encoding_d.h
 *    Macro definitions for pg_attribute_encoding
 *
 * Portions Copyright (c) 1996-2023, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef PG_ATTRIBUTE_ENCODING_D_H
#define PG_ATTRIBUTE_ENCODING_D_H

#define AttributeEncodingRelationId 7033
#define AttributeEncodingAttrelidIndexId 7039
#define AttributeEncodingAttrelidAttnumIndexId 7040

#define Anum_pg_attribute_encoding_attrelid 1
#define Anum_pg_attribute_encoding_attnum 2
#define Anum_pg_attribute_encoding_attoptions 3

#define Natts_pg_attribute_encoding 3


#endif							/* PG_ATTRIBUTE_ENCODING_D_H */
