/*-------------------------------------------------------------------------
 *
 * pg_auth_time_constraint_d.h
 *    Macro definitions for pg_auth_time_constraint
 *
 * Portions Copyright (c) 1996-2023, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef PG_AUTH_TIME_CONSTRAINT_D_H
#define PG_AUTH_TIME_CONSTRAINT_D_H

#define AuthTimeConstraintRelationId 6070
#define AuthTimeConstraint_Rowtype_Id 6071
#define AuthTimeConstraintAuthIdIndexId 6449

#define Anum_pg_auth_time_constraint_authid 1
#define Anum_pg_auth_time_constraint_start_day 2
#define Anum_pg_auth_time_constraint_start_time 3
#define Anum_pg_auth_time_constraint_end_day 4
#define Anum_pg_auth_time_constraint_end_time 5

#define Natts_pg_auth_time_constraint 5


#endif							/* PG_AUTH_TIME_CONSTRAINT_D_H */
