/*-------------------------------------------------------------------------
 *
 * pg_compression_d.h
 *    Macro definitions for pg_compression
 *
 * Portions Copyright (c) 1996-2023, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef PG_COMPRESSION_D_H
#define PG_COMPRESSION_D_H

#define CompressionRelationId 7056
#define CompressionCompnameIndexId 7059

#define Anum_pg_compression_compname 1
#define Anum_pg_compression_compconstructor 2
#define Anum_pg_compression_compdestructor 3
#define Anum_pg_compression_compcompressor 4
#define Anum_pg_compression_compdecompressor 5
#define Anum_pg_compression_compvalidator 6
#define Anum_pg_compression_compowner 7

#define Natts_pg_compression 7


#endif							/* PG_COMPRESSION_D_H */
