/*-------------------------------------------------------------------------
 *
 * pg_proc_callback_d.h
 *    Macro definitions for pg_proc_callback
 *
 * Portions Copyright (c) 1996-2023, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef PG_PROC_CALLBACK_D_H
#define PG_PROC_CALLBACK_D_H

#define ProcCallbackRelationId 7176
#define ProcCallbackProfnoidPromethodIndexId 9926

#define Anum_pg_proc_callback_profnoid 1
#define Anum_pg_proc_callback_procallback 2
#define Anum_pg_proc_callback_promethod 3

#define Natts_pg_proc_callback 3


#endif							/* PG_PROC_CALLBACK_D_H */
