/*-------------------------------------------------------------------------
 *
 * pg_resgroupcapability_d.h
 *    Macro definitions for pg_resgroupcapability
 *
 * Portions Copyright (c) 1996-2023, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef PG_RESGROUPCAPABILITY_D_H
#define PG_RESGROUPCAPABILITY_D_H

#define ResGroupCapabilityRelationId 6439
#define ResGroupCapabilityResgroupidResLimittypeIndexId 6445
#define ResGroupCapabilityResgroupidIndexId 6446

#define Anum_pg_resgroupcapability_resgroupid 1
#define Anum_pg_resgroupcapability_reslimittype 2
#define Anum_pg_resgroupcapability_value 3

#define Natts_pg_resgroupcapability 3


#endif							/* PG_RESGROUPCAPABILITY_D_H */
