/*-------------------------------------------------------------------------
 *
 * pg_resqueuecapability_d.h
 *    Macro definitions for pg_resqueuecapability
 *
 * Portions Copyright (c) 1996-2023, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef PG_RESQUEUECAPABILITY_D_H
#define PG_RESQUEUECAPABILITY_D_H

#define ResQueueCapabilityRelationId 6060
#define ResQueueCapabilityResqueueidIndexId 6442
#define ResQueueCapabilityRestypidIndexId 6443

#define Anum_pg_resqueuecapability_resqueueid 1
#define Anum_pg_resqueuecapability_restypid 2
#define Anum_pg_resqueuecapability_ressetting 3

#define Natts_pg_resqueuecapability 3


#endif							/* PG_RESQUEUECAPABILITY_D_H */
