/*-------------------------------------------------------------------------
 *
 * pg_resourcetype_d.h
 *    Macro definitions for pg_resourcetype
 *
 * Portions Copyright (c) 1996-2023, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef PG_RESOURCETYPE_D_H
#define PG_RESOURCETYPE_D_H

#define ResourceTypeRelationId 6059
#define ResourceTypeOidIndexId 6061
#define ResourceTypeRestypidIndexId 6062
#define ResourceTypeResnameIndexId 6063

#define Anum_pg_resourcetype_oid 1
#define Anum_pg_resourcetype_resname 2
#define Anum_pg_resourcetype_restypid 3
#define Anum_pg_resourcetype_resrequired 4
#define Anum_pg_resourcetype_reshasdefault 5
#define Anum_pg_resourcetype_reshasdisable 6
#define Anum_pg_resourcetype_resdefaultsetting 7
#define Anum_pg_resourcetype_resdisabledsetting 8

#define Natts_pg_resourcetype 8


#endif							/* PG_RESOURCETYPE_D_H */
