/*-------------------------------------------------------------------------
 *
 * pg_resgroup_d.h
 *    Macro definitions for pg_resgroup
 *
 * Portions Copyright (c) 1996-2023, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef PG_RESGROUP_D_H
#define PG_RESGROUP_D_H

#define ResGroupRelationId 6436
#define ResGroupOidIndexId 6447
#define ResGroupRsgnameIndexId 6444

#define Anum_pg_resgroup_oid 1
#define Anum_pg_resgroup_rsgname 2
#define Anum_pg_resgroup_parent 3

#define Natts_pg_resgroup 3

#define DEFAULTRESGROUP_OID 6437
#define ADMINRESGROUP_OID 6438
#define DEFAULTAUXILIARY_OID 6441

#endif							/* PG_RESGROUP_D_H */
