/*-------------------------------------------------------------------------
 *
 * pg_resqueue_d.h
 *    Macro definitions for pg_resqueue
 *
 * Portions Copyright (c) 1996-2023, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef PG_RESQUEUE_D_H
#define PG_RESQUEUE_D_H

#define ResQueueRelationId 6026
#define ResQueueOidIndexId 6027
#define ResQueueRsqnameIndexId 6028

#define Anum_pg_resqueue_oid 1
#define Anum_pg_resqueue_rsqname 2
#define Anum_pg_resqueue_rsqcountlimit 3
#define Anum_pg_resqueue_rsqcostlimit 4
#define Anum_pg_resqueue_rsqovercommit 5
#define Anum_pg_resqueue_rsqignorecostlimit 6

#define Natts_pg_resqueue 6

#define DEFAULTRESQUEUE_OID 6055

#endif							/* PG_RESQUEUE_D_H */
