/*-------------------------------------------------------------------------
 *
 * pg_stat_last_operation_d.h
 *    Macro definitions for pg_stat_last_operation
 *
 * Portions Copyright (c) 1996-2023, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef PG_STAT_LAST_OPERATION_D_H
#define PG_STAT_LAST_OPERATION_D_H

#define StatLastOpRelationId 6052
#define StatLastOpClassidObjidStaactionnameIndexId 6054

#define Anum_pg_stat_last_operation_classid 1
#define Anum_pg_stat_last_operation_objid 2
#define Anum_pg_stat_last_operation_staactionname 3
#define Anum_pg_stat_last_operation_stasysid 4
#define Anum_pg_stat_last_operation_stausename 5
#define Anum_pg_stat_last_operation_stasubtype 6
#define Anum_pg_stat_last_operation_statime 7

#define Natts_pg_stat_last_operation 7


#endif							/* PG_STAT_LAST_OPERATION_D_H */
