/*-------------------------------------------------------------------------
 *
 * pg_stat_last_shoperation_d.h
 *    Macro definitions for pg_stat_last_shoperation
 *
 * Portions Copyright (c) 1996-2023, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef PG_STAT_LAST_SHOPERATION_D_H
#define PG_STAT_LAST_SHOPERATION_D_H

#define StatLastShOpRelationId 6056
#define StatLastShOpClassidObjidIndexId 6057
#define StatLastShOpClassidObjidStaactionnameIndexId 6058

#define Anum_pg_stat_last_shoperation_classid 1
#define Anum_pg_stat_last_shoperation_objid 2
#define Anum_pg_stat_last_shoperation_staactionname 3
#define Anum_pg_stat_last_shoperation_stasysid 4
#define Anum_pg_stat_last_shoperation_stausename 5
#define Anum_pg_stat_last_shoperation_stasubtype 6
#define Anum_pg_stat_last_shoperation_statime 7

#define Natts_pg_stat_last_shoperation 7


#endif							/* PG_STAT_LAST_SHOPERATION_D_H */
