/*-------------------------------------------------------------------------
 *
 * pg_type_encoding_d.h
 *    Macro definitions for pg_type_encoding
 *
 * Portions Copyright (c) 1996-2023, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef PG_TYPE_ENCODING_D_H
#define PG_TYPE_ENCODING_D_H

#define TypeEncodingRelationId 7032
#define TypeEncodingTypidIndexId 7038

#define Anum_pg_type_encoding_typid 1
#define Anum_pg_type_encoding_typoptions 2

#define Natts_pg_type_encoding 2


#endif							/* PG_TYPE_ENCODING_D_H */
