---

version: "3"
services:
  #image can be either hub.adsw.io/library/gpdb7_regress:${BRANCH_NAME}-x86-64 or
  #hub.adsw.io/library/gpdb7_regress:${BRANCH_NAME}-ppc64le depending on the arch
  cdw:
    image: "${IMAGE}"
    working_dir: /home/gpadmin
    hostname: cdw
    volumes:
      - "$PWD/ssh_keys/id_rsa:/home/gpadmin/.ssh/id_rsa"
      - "$PWD/ssh_keys/id_rsa.pub:/home/gpadmin/.ssh/id_rsa.pub"
      - "$PWD/allure-results:/tmp/allure-results"
    privileged: true
    sysctls:
      kernel.sem: 500 1024000 200 4096
    init: true
    entrypoint: >
      sleep infinity
  sdw1:
    image: "${IMAGE}"
    privileged: true
    hostname: sdw1
    volumes:
      - "$PWD/ssh_keys/id_rsa:/home/gpadmin/.ssh/id_rsa"
      - "$PWD/ssh_keys/id_rsa.pub:/home/gpadmin/.ssh/id_rsa.pub"
    sysctls:
      kernel.sem: 500 1024000 200 4096
    init: true
    entrypoint: >
      sleep infinity
  sdw2:
    image: "${IMAGE}"
    privileged: true
    hostname: sdw2
    volumes:
      - "$PWD/ssh_keys/id_rsa:/home/gpadmin/.ssh/id_rsa"
      - "$PWD/ssh_keys/id_rsa.pub:/home/gpadmin/.ssh/id_rsa.pub"
    sysctls:
      kernel.sem: 500 1024000 200 4096
    init: true
    entrypoint: >
      sleep infinity
  sdw3:
    image: "${IMAGE}"
    privileged: true
    hostname: sdw3
    volumes:
      - "$PWD/ssh_keys/id_rsa:/home/gpadmin/.ssh/id_rsa"
      - "$PWD/ssh_keys/id_rsa.pub:/home/gpadmin/.ssh/id_rsa.pub"
    sysctls:
      kernel.sem: 500 1024000 200 4096
    init: true
    entrypoint: >
      sleep infinity
