---

version: "3"
services:
  #image can be either hub.adsw.io/library/gpdb6_regress:${BRANCH_NAME}-x86-64 or
  #hub.adsw.io/library/gpdb6_regress:${BRANCH_NAME}-ppc64le depending on the arch
  mdw:
    image: "${IMAGE}"
    working_dir: /home/gpadmin
    hostname: mdw
    volumes:
      - "$PWD/ssh_keys/id_rsa:/home/gpadmin/.ssh/id_rsa"
      - "$PWD/ssh_keys/id_rsa.pub:/home/gpadmin/.ssh/id_rsa.pub"
      - "$PWD/allure-results:/tmp/allure-results"
    privileged: true
    sysctls:
      kernel.sem: 500 1024000 200 4096
    entrypoint: >
      bash -c "set -e && tail -f /home/gpadmin/gpdb_src/README.md"
  sdw1:
    image: "${IMAGE}"
    privileged: true
    hostname: sdw1
    volumes:
      - "$PWD/ssh_keys/id_rsa:/home/gpadmin/.ssh/id_rsa"
      - "$PWD/ssh_keys/id_rsa.pub:/home/gpadmin/.ssh/id_rsa.pub"
    sysctls:
      kernel.sem: 500 1024000 200 4096
    entrypoint: >
      bash -c "set -e && tail -f /home/gpadmin/gpdb_src/README.md"
  sdw2:
    image: "${IMAGE}"
    privileged: true
    hostname: sdw2
    volumes:
      - "$PWD/ssh_keys/id_rsa:/home/gpadmin/.ssh/id_rsa"
      - "$PWD/ssh_keys/id_rsa.pub:/home/gpadmin/.ssh/id_rsa.pub"
    sysctls:
      kernel.sem: 500 1024000 200 4096
    entrypoint: >
      bash -c "set -e && tail -f /home/gpadmin/gpdb_src/README.md"
  sdw3:
    image: "${IMAGE}"
    privileged: true
    hostname: sdw3
    volumes:
      - "$PWD/ssh_keys/id_rsa:/home/gpadmin/.ssh/id_rsa"
      - "$PWD/ssh_keys/id_rsa.pub:/home/gpadmin/.ssh/id_rsa.pub"
    sysctls:
      kernel.sem: 500 1024000 200 4096
    entrypoint: >
      bash -c "set -e && tail -f /home/gpadmin/gpdb_src/README.md"
