FROM ubuntu:22.04 as base

RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*  

WORKDIR /home/gpadmin

RUN mkdir gg6; \
    cd gg6; \
    git clone https://github.com/GreengageDB/greengage.git; 


RUN set -eux; \
    /home/gpadmin/gg6/greengage/README.ubuntu.bash; \
    ln -s python2 /usr/bin/python; \
# Install pg_bsd_indent used by pgindent utility
    wget https://ftp.postgresql.org/pub/dev/pg_bsd_indent-1.3.tar.gz -O - | tar -xzf -; \
    make install -C pg_bsd_indent; \
    rm -r pg_bsd_indent; \
# The en_US.UTF-8 locale is needed to run GPDB
    locale-gen en_US.UTF-8; \
# To run sshd directly, but not using `/etc/init.d/ssh start`
    mkdir /run/sshd; \
# Alter precedence in favor of IPv4 during resolving
    echo 'precedence ::ffff:0:0/96  100' >> /etc/gai.conf; \
# Packages for tests
    DEBIAN_FRONTEND=noninteractive \
        apt install -y krb5-kdc krb5-admin-server fakeroot sudo python-pip \
            openjdk-11-jdk protobuf-compiler python3-dev; \
# Install allure-behave for behave tests
    pip2 install allure-behave==2.4.0; \
    pip2 cache purge;\
    python -m pip install psutil; 
    
COPY . gpdb_src

WORKDIR /home/gpadmin/gpdb_src

RUN ./README.Ubuntu.bash


FROM base as build6

ENV TARGET_OS_VERSION=22
ENV TARGET_OS=ubuntu
ENV LANG=en_US.UTF-8

WORKDIR /home/gpadmin/gg6/greengage

RUN ./configure --with-perl --with-python --with-libxml --with-gssapi --prefix=/usr/local/gpdb6


# Compile and install
RUN make -j"$(nproc)"
RUN make -j"$(nproc)" install


FROM base as build7

ENV TARGET_OS_VERSION=22
ENV TARGET_OS=ubuntu
ENV LANG=en_US.UTF-8

WORKDIR /home/gpadmin/gpdb_src

RUN ./configure --with-perl --with-python --with-libxml --with-gssapi --prefix=/usr/local/gpdb7

# Compile and install
RUN make -j"$(nproc)"
RUN make -j"$(nproc)" install

FROM base AS test

WORKDIR /home/gpadmin

COPY --from=build6 /home/gpadmin/gg6/greengage gpdb_src6
COPY --from=build6 /usr/local/gpdb6 gpdb6
COPY --from=build7 /usr/local/gpdb7  /usr/local/greengage-db-devel
COPY --from=build7 /home/gpadmin/gpdb_src gpdb_src


RUN /home/gpadmin/gpdb_src/concourse/scripts/setup_gpadmin_user.bash

