---

version: "3"
services:
  cdw:
    image: "${IMAGE}"
    working_dir: /home/gpadmin
    hostname: cdw
    volumes:
      - "$PWD/ssh_keys/id_rsa:/home/gpadmin/.ssh/id_rsa"
      - "$PWD/ssh_keys/id_rsa.pub:/home/gpadmin/.ssh/id_rsa.pub"
      - "$PWD/allure-results:/tmp/allure-results"
      - "$PWD/logs_cdw:/logs"
    privileged: true
    sysctls:
      kernel.sem: 500 1024000 200 4096
    init: true
    ulimits:
      nofile: 65535
    entrypoint: >
      sleep infinity
  sdw1:
    image: "${IMAGE}"
    privileged: true
    hostname: sdw1
    volumes:
      - "$PWD/ssh_keys/id_rsa:/home/gpadmin/.ssh/id_rsa"
      - "$PWD/ssh_keys/id_rsa.pub:/home/gpadmin/.ssh/id_rsa.pub"
      - "$PWD/logs_sdw1:/logs"
    sysctls:
      kernel.sem: 500 1024000 200 4096
    init: true
    ulimits:
      nofile: 65535
    entrypoint: >
      sleep infinity
  sdw2:
    image: "${IMAGE}"
    privileged: true
    hostname: sdw2
    volumes:
      - "$PWD/ssh_keys/id_rsa:/home/gpadmin/.ssh/id_rsa"
      - "$PWD/ssh_keys/id_rsa.pub:/home/gpadmin/.ssh/id_rsa.pub"
    sysctls:
      kernel.sem: 500 1024000 200 4096
    init: true
    ulimits:
      nofile: 65535
    entrypoint: >
      sleep infinity
  sdw3:
    image: "${IMAGE}"
    privileged: true
    hostname: sdw3
    volumes:
      - "$PWD/ssh_keys/id_rsa:/home/gpadmin/.ssh/id_rsa"
      - "$PWD/ssh_keys/id_rsa.pub:/home/gpadmin/.ssh/id_rsa.pub"
    sysctls:
      kernel.sem: 500 1024000 200 4096
    init: true
    ulimits:
      nofile: 65535
    entrypoint: >
      sleep infinity
