# FILE:    ci/Dockerfile.rockylinux
# CONTEXT: Build Greengage on Rocky Linux <OS_VERSION>
# PURPOSE: Multi-stage Docker build for Greengage database

ARG OS_VERSION=8

FROM rockylinux:${OS_VERSION} AS base
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
WORKDIR /home/gpadmin

ARG OS_VERSION
ENV OS_VERSION=${OS_VERSION}

ARG LLVM_VERSION=14.0.6
ARG LLVM_ARCHIVE=clang+llvm-14.0.6-x86_64-linux-gnu-rhel-8.4

COPY README.Rhel-Rocky.bash ./
RUN set -eux; \
    IS_DOCKER_BUILD=true ./README.Rhel-Rocky.bash; \
    rm README.Rhel-Rocky.bash; \
# Install LLVM + clang v14; default LLVM/clang v21 is incompatible
    wget --no-hsts -q https://github.com/llvm/llvm-project/releases/download/llvmorg-${LLVM_VERSION}/${LLVM_ARCHIVE}.tar.xz; \
    tar -C /usr --strip-components=1 -xf ${LLVM_ARCHIVE}.tar.xz; \
    rm -f ${LLVM_ARCHIVE}.tar.xz; \
# Install pg_bsd_indent used by pgindent utility
    wget --progress=dot:giga --no-hsts https://ftp.postgresql.org/pub/dev/pg_bsd_indent-1.3.tar.gz -O - | tar -xzf -; \
    make install -C pg_bsd_indent; \
    rm -r pg_bsd_indent; \
# To run sshd directly, but not using service
    mkdir -p /run/sshd; \
# Alter precedence in favor of IPv4 during resolving
    echo 'precedence ::ffff:0:0/96  100' >> /etc/gai.conf; \
# Upgrade pip to support current package versions
    python3 -m pip install --no-cache-dir --upgrade pip; \
# Install Python packages
    python3 -m pip install --no-cache-dir allure-behave==2.4.0 \
      behave~=1.2.6 \
      coverage~=4.5 \
      gsutil \
      'mock<=5.0.0' \
      protobuf==3.20.0; \
# Cleanup to reduce image size
    dnf clean all; \
    rm -rf /tmp/* /var/tmp/* /var/cache/man/

ENV LANG=en_US.UTF-8
ENV CONFIGURE_FLAGS="--enable-debug-extensions --with-gssapi --enable-cassert --enable-debug --enable-depend"

FROM base AS build

COPY . gpdb_src

RUN mkdir bin_gpdb

ENV TARGET_OS=rockylinux \
    OUTPUT_ARTIFACT_DIR=bin_gpdb

# Compile with running mocking tests
RUN gpdb_src/concourse/scripts/compile_gpdb.bash

FROM base AS code
COPY . gpdb_src
RUN rm -rf gpdb_src/.git/

FROM base AS test

COPY --from=code  /home/gpadmin/gpdb_src gpdb_src
COPY --from=build /home/gpadmin/bin_gpdb bin_gpdb
COPY --from=build /home/gpadmin/gpdb_src/VERSION gpdb_src
