ARG OS_VERSION=22.04

FROM ubuntu:${OS_VERSION} AS base
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
WORKDIR /home/gpadmin

ENV PIP_BREAK_SYSTEM_PACKAGES=1

COPY README.ubuntu.bash ./
COPY gpMgmt/bin/gpload_test/pytest_requirement.txt ./
RUN set -eux; \
    ./README.ubuntu.bash; \
    rm README.ubuntu.bash; \
# Set Python 2 as default when needed
    test "$(lsb_release -sr)" == "22.04" && ln -s python2 /usr/bin/python; \
# Install pg_bsd_indent used by pgindent utility
    wget --progress=dot:giga --no-hsts https://ftp.postgresql.org/pub/dev/pg_bsd_indent-1.3.tar.gz -O - | tar -xzf -; \
    make install -C pg_bsd_indent; \
    rm -r pg_bsd_indent; \
# The en_US.UTF-8 locale is needed to run GPDB
    locale-gen en_US.UTF-8; \
# To run sshd directly, but not using `/etc/init.d/ssh start`
    mkdir /run/sshd; \
# Alter precedence in favor of IPv4 during resolving
    echo 'precedence ::ffff:0:0/96  100' >> /etc/gai.conf; \
# Install allure-behave for behave tests
    python -m pip install --no-cache-dir allure-behave==2.4.0 mock==3.0.5 && \
# Install pytest for gpload test
    python -m pip install --no-cache-dir -r pytest_requirement.txt && \
    rm pytest_requirement.txt && \
# Cleanup to reduce image size
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /var/cache/man/

ENV LANG=en_US.UTF-8
ENV CONFIGURE_FLAGS="--enable-debug-extensions --with-gssapi --enable-cassert --enable-debug --enable-depend"

FROM base AS build

COPY . gpdb_src

RUN mkdir bin_gpdb

ENV TARGET_OS=ubuntu \
    OUTPUT_ARTIFACT_DIR=bin_gpdb

# Compile with running mocking tests
# Use python3 to compile into GPDB's plpython3u
RUN test "$(lsb_release -sr)" == "22.04" && export PYTHON3=python3; \
    gpdb_src/concourse/scripts/compile_gpdb.bash

FROM base AS code
# Use --exclude, when it will be available in stable syntax.
COPY . gpdb_src
RUN rm -rf gpdb_src/.git/

FROM base AS test

COPY --from=code  /home/gpadmin/gpdb_src gpdb_src
COPY --from=build /home/gpadmin/bin_gpdb bin_gpdb
COPY --from=build /home/gpadmin/gpdb_src/VERSION gpdb_src

# Install entab used by pgindent utility.
# This should be done using gpdb sources.
RUN make -C gpdb_src/src/tools/entab install clean
