FROM ubuntu:22.04

ARG UBUNTU_MAIN_MIRROR=http://archive.ubuntu.com/ubuntu
ARG UBUNTU_UPDATES_MIRROR=http://archive.ubuntu.com/ubuntu
ARG UBUNTU_BACKPORTS_MIRROR=http://archive.ubuntu.com/ubuntu
ARG UBUNTU_SECURITY_MIRROR=http://security.ubuntu.com/ubuntu

RUN sed -i \
      -e "s|http://archive.ubuntu.com/ubuntu/ jammy |${UBUNTU_MAIN_MIRROR}/ jammy |g" \
      -e "s|http://archive.ubuntu.com/ubuntu/ jammy-updates |${UBUNTU_UPDATES_MIRROR}/ jammy-updates |g" \
      -e "s|http://archive.ubuntu.com/ubuntu/ jammy-backports |${UBUNTU_BACKPORTS_MIRROR}/ jammy-backports |g" \
      -e "s|http://security.ubuntu.com/ubuntu/ jammy-security |${UBUNTU_SECURITY_MIRROR}/ jammy-security |g" \
      /etc/apt/sources.list && \
    apt update && apt install -y git parallel clang-format-11 && \
    ln -s /usr/bin/clang-format-11 /usr/bin/clang-format

WORKDIR /opt/gpdb_src

COPY . /opt/gpdb_src

ENV CLANG_FORMAT=clang-format-11

ENTRYPOINT src/tools/fmt gen && git diff --exit-code && src/tools/fmt chk
