name: Docker Build and Push

on:
  #push:
  #  branches: ["main"]
  pull_request:
    paths:
      - 'concourse/scripts/**'
      - 'src/**'
      - '.github/workflows/**'
      - '.github/scripts/**'
      - 'ci/**'

jobs:
  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #         filter: tree:0
  #         submodules: 'recursive'

  #     - name: Login to GHCR
  #       uses: docker/login-action@v3
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3
  #       with:
  #         version: latest

  #     - name: Build and export
  #       uses: docker/build-push-action@v6
  #       with:
  #         context: .
  #         file: ./ci/Dockerfile.ubuntu
  #         cache-from: type=gha
  #         cache-to: type=gha,mode=max
  #         push: true # ${{ github.event_name == 'push' }}
  #         tags: |
  #           ghcr.io/stolb27/gpdb6_u22:${{ github.sha }}

  # regression:
  #   needs: build
  #   runs-on: ubuntu-latest

  #   strategy:
  #     matrix:
  #       optimizer: [on, off]

  #   steps:
  #     - name: Move /var/lib/docker/
  #       run: sudo mv /var/lib/docker/ "${GITHUB_WORKSPACE}/docker"

  #     - name: Maximize build space
  #       uses: easimon/maximize-build-space@master
  #       with:
  #         root-reserve-mb: 512
  #         temp-reserve-mb: 32
  #         swap-size-mb: 32
  #         remove-dotnet: 'true'
  #         remove-android: 'true'
  #         remove-haskell: 'true'
  #         remove-codeql: 'true'
  #         remove-docker-images: 'true'
  #         build-mount-path: '/var/lib/docker/'

  #     - name: Restore /var/lib/docker/
  #       run: sudo sh -c "mv ${GITHUB_WORKSPACE}/docker/* /var/lib/docker"

  #     - name: Login to GHCR
  #       uses: docker/login-action@v3
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3
  #       with:
  #         version: latest

  #     - name: Regression test with optimizer=${{ matrix.optimizer }}
  #       run: |
  #         docker run --name gpdb6_opt_on --rm -e TEST_OS=ubuntu \
  #           -e MAKE_TEST_COMMAND="-k PGOPTIONS='-c optimizer=${{ matrix.optimizer }}' installcheck-world" \
  #           --sysctl 'kernel.sem=500 1024000 200 4096' ghcr.io/stolb27/gpdb6_u22:${{ github.sha }} \
  #           bash /home/gpadmin/gpdb_src/concourse/scripts/ic_gpdb.bash

  resgroup:
    # needs: build
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout repository
      #   uses: actions/checkout@v4
      #   with:
      #     fetch-depth: 0
      #     filter: tree:0
      #     submodules: 'recursive'

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Setup Lima
        uses: lima-vm/lima-actions/setup@v1
        id: lima-actions-setup

      - uses: actions/cache@v4
        with:
          path: ~/.cache/lima
          key: lima-${{ steps.lima-actions-setup.outputs.version }}

      - name: Start the guest VM
        run: |
          set -eux
          limactl start --name=default template://docker-rootful.yaml
          # containerd=none is set because the built-in containerd support conflicts with Docker
          # limactl start \
          #   --name=default \
          #   --cpus=4 \
          #   --memory=8 \
          #   --containerd=none \
          #   --mount-type 9p \
          #   --set '.mounts=[{"location":"~/","writable":true, "9p": { "securityModel": "mapped-xattr", "cache": "mmap"}}] | .portForwards=[{"guestSocket":"/var/run/docker.sock","hostSocket":"{{.Dir}}/sock/docker.sock"}]' \
          #   template://almalinux-8

      # - name: Install dockerd in the guest VM
      #   run: |
      #     set -eux
      #     lima sudo mkdir -p /etc/systemd/system/docker.socket.d
      #     cat <<-EOF | lima sudo tee /etc/systemd/system/docker.socket.d/override.conf
      #     [Socket]
      #     SocketUser=$(whoami)
      #     EOF
      #     lima sudo dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
      #     lima sudo dnf -q -y install docker-ce --nobest
      #     lima sudo systemctl enable --now docker

      - name: Configure the host to use dockerd in the guest VM
        run: |
          set -eux
          sudo systemctl disable --now docker.service docker.socket
          export DOCKER_HOST="unix://$(limactl ls --format '{{.Dir}}/sock/docker.sock' default)"
          echo "DOCKER_HOST=${DOCKER_HOST}" >>$GITHUB_ENV
          docker info
          docker version

      - name: Resource groups test
        run: |
          export IMAGE="ghcr.io/stolb27/gpdb6_u22:e4a4908c437d62ec8291958e432b4305c0a9e03b"
          docker run --rm $IMAGE bash -c "mount | grep cgroup"
          # ./ci/scripts/run_resgroup_test.bash
