name: Docker Build and Push

on:
  #push:
  #  branches: ["main"]
  pull_request:
    paths:
      - 'concourse/scripts/**'
      - 'src/**'
      - '.github/workflows/**'
      - '.github/scripts/**'
      - 'ci/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: Build Docker image
        run: |
          docker build -t "gpdb6_u22:${GITHUB_SHA}" -f ci/Dockerfile.ubuntu .

  regression:
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        optimizer: [on, off]

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: Regression test with optimizer=${{ matrix.optimizer }}
        run: |
          docker run --name gpdb6_opt_on --rm -e TEST_OS=centos \
            -e MAKE_TEST_COMMAND="-k PGOPTIONS='-c optimizer=${{ matrix.optimizer }}' installcheck-world" \
            --sysctl 'kernel.sem=500 1024000 200 4096' gpdb6_u22::${GITHUB_SHA} \
            bash /home/gpadmin/gpdb_src/concourse/scripts/ic_gpdb.bash
