# Main CI pipeline orchestrating build, test, and upload stages
name: Greengage CI

env:
  version: 7

on:
  push:
    tags: ['7.*']  # Trigger on tags for versioned releases
  pull_request:
    branches: ['*']  # Trigger on pull requests for all branches

jobs:
  build:
    strategy:
      fail-fast: true  # Stop on any failure in the matrix
      matrix:
        target_os: [ubuntu] #, rockylinux]
    permissions:
      packages: write  # Required for GHCR access
    uses: greengagedb/greengage-ci/.github/workflows/greengage-reusable-build.yml@main
    with:
      version: 7
      target_os: ${{ matrix.target_os }}
    secrets:
      ghcr_token: ${{ secrets.GITHUB_TOKEN }}  # Custom token for pushing image with commit SHA tag

  behave-tests:
    needs: build  # Wait for build to complete
    strategy:
      fail-fast: true
      matrix:
        target_os: [ubuntu] #, rockylinux]
    uses: greengagedb/greengage-ci/.github/workflows/greengage-reusable-tests-behave.yml@main
    with:
      version: 7
      target_os: ${{ matrix.target_os }}
    secrets:
      ghcr_token: ${{ secrets.GITHUB_TOKEN }}  # Token for test environment access

  regression-tests:
    needs: build
    strategy:
      fail-fast: true
      matrix:
        target_os: [ubuntu, centos]
    uses: greengagedb/greengage-ci/.github/workflows/greengage-reusable-tests-regression.yml@main
    with:
      version: 7
      target_os: ${{ matrix.target_os }}
    secrets:
      ghcr_token: ${{ secrets.GITHUB_TOKEN }}  # Token for test environment access

  orca-tests:
    needs: build
    strategy:
      fail-fast: true
      matrix:
        target_os: [ubuntu] #, rockylinux]
    uses: greengagedb/greengage-ci/.github/workflows/greengage-reusable-tests-orca.yml@main
    with:
      version: 7
      target_os: ${{ matrix.target_os }}
    secrets:
      ghcr_token: ${{ secrets.GITHUB_TOKEN }}  # Token for test environment access

  # resgroup-tests:
  #   needs: build
  #   strategy:
  #     fail-fast: true
  #     matrix:
  #       target_os: [ubuntu] #, rockylinux]
  #   uses: greengagedb/greengage-ci/.github/workflows/greengage-reusable-tests-resgroup.yml@main
  #   with:
  #     version: 7
  #     target_os: ${{ matrix.target_os }}
  #   secrets:
  #     ghcr_token: ${{ secrets.GITHUB_TOKEN }}  # Token for test environment access

  upload:
    needs: [behave-tests, regression-tests, orca-tests] #, resgroup-tests]  # Wait for all tests
    strategy:
      fail-fast: true
      matrix:
        target_os: [ubuntu] #, rockylinux]
    permissions:
      packages: write  # Required for GHCR access
    uses: greengagedb/greengage-ci/.github/workflows/greengage-reusable-upload.yml@main
    with:
      version: 7
      target_os: ${{ matrix.target_os }}
    secrets:
      ghcr_token: ${{ secrets.GITHUB_TOKEN }}  # Custom token for retagging and pushing final image
