# .github/workflows/greengage-release.yml
name: Greengage release

on:
  release:
    types: [released]

jobs:
  upload-to-release:
    strategy:
      fail-fast: false
      matrix:
        include:
        - target_os: ubuntu
          target_os_version: '22.04'
          extensions:  deb ddeb
          artifact_prefix: deb-packages
        - target_os: ubuntu
          target_os_version: '24.04'
          extensions:  deb ddeb
          artifact_prefix: deb-packages
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      actions: read
    steps:
      - name: Upload packages to release
        uses: greengagedb/greengage-ci/.github/actions/upload-pkgs-to-release@CI-5861
        with:
          extensions:        ${{ matrix.extensions }}
          artifact_prefix:   ${{ matrix.artifact_prefix }}
          target_os:         ${{ matrix.target_os }}
          target_os_version: ${{ matrix.target_os_version }}
