# Release creation workflow
name: Greengage release

on:
  release:
    types: [released]

jobs:
  upload-to-release:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target_os: ubuntu
            package_dir: deb-packages
            extensions: deb ddeb
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      actions: read
    steps:
      - name: Upload packages to release
        uses: greengagedb/greengage-ci/.github/actions/upload-pkgs-to-release@CI-5791
        with:
          extensions:   ${{ matrix.extensions }}
          package_dir:  ${{ matrix.package_dir }}
          target_os:    ${{ matrix.target_os }}
