name: Greengage Auto Build

on:
  push:
    tags: ['7.*']
  pull_request:
    branches: ['*']
    tags: ['7.*']

env:
  version: 7

jobs:
  build-ubuntu:
    # Job for building on Ubuntu, runs in parallel with other jobs
    uses: GreengageDB/greengage-ci/.github/workflows/greengage-reusable-build.yml@main
    with:
      version: ${{ env.version }}
      target_os: ubuntu
      target_os_version: ''
    secrets:
      # GitHub token for authentication
      ghcr_token: ${{ secrets.GITHUB_TOKEN }}

  # build-rockylinux:
  #   # Job for building on Rocky Linux, runs in parallel with other jobs
  #   uses: GreengageDB/greengage-ci/.github/workflows/greengage-reusable-build.yml@main
  #   with:
  #     version: ${{ env.version }}
  #     target_os: rockylinux
  #     target_os_version: 8
  #   secrets:
  #     # GitHub token for authentication
  #     ghcr_token: ${{ secrets.GITHUB_TOKEN }}
